[tool.poetry]
name = "scratchy-pad"
version = "0.1.0"
description = ""
authors = ["none <none>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
